language: java

before_install:
  # Ripped most of this from https://github.com/pestrada/android-tdd-playground/blob/master/.travis.yml
  ### This version is necessary if the standard script stops working.

  # Install base Android SDK
  - ANDROID_SDK_VERSION="23"
  - ANDROID_SDK_FILE=android-sdk_r$(printf %s $ANDROID_SDK_VERSION)-linux.tgz
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/$ANDROID_SDK_FILE
  - tar xzf $ANDROID_SDK_FILE
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

  # Try to autogenerate the current SDK and BUILD_TOOLS versions
  - SDK_VERSION=android-`grep compileSdkVersion MPDroid/build.gradle | sed -e 's/.* //'`
  - BUILD_TOOLS=build-tools-`grep buildToolsVersion MPDroid/build.gradle | sed -e 's/.* "//' | sed -e 's/"$//'`

  # Install required components.
  # For a full list, run `android list sdk -a --extended`
  # Other relevant API's
  - echo yes | android update sdk --filter $BUILD_TOOLS --no-ui --force
  - echo yes | android update sdk --filter platform-tools --no-ui --force
  - echo yes | android update sdk --filter $SDK_VERSION --no-ui --force
  - echo yes | android update sdk --filter extra-android-support --no-ui --force
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force

script:
  - ./gradlew build
